"""Finite group abstractions and concrete families.

Provides a :class:`Group` base plus factory helpers for symmetric,
cyclic, and dihedral groups.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from math import gcd
from functools import reduce
from itertools import product as iter_product
from typing import Callable, FrozenSet, Hashable, Iterator, Set, Tuple


class Group(ABC):
    """Abstract finite group.

    Subclasses must provide :attr:`elements`, a binary ``operation``,
    the ``identity`` element, and an ``inverse`` mapping.
    """

    # --- abstract interface ------------------------------------------------

    @property
    @abstractmethod
    def elements(self) -> FrozenSet[Hashable]:
        """Return the elements of the group as an immutable set."""

    @abstractmethod
    def operation(self, a: Hashable, b: Hashable) -> Hashable:
        """Return *a* ∘ *b* (the group binary operation)."""

    @property
    @abstractmethod
    def identity(self) -> Hashable:
        """Return the identity element."""

    @abstractmethod
    def inverse(self, a: Hashable) -> Hashable:
        """Return the inverse of *a*."""

    # --- derived helpers ---------------------------------------------------

    def order(self) -> int:
        """Return ``|G|``, the number of elements."""
        return len(self.elements)

    def is_abelian(self) -> bool:
        """Return ``True`` if *G* is commutative.

        Checks every pair of elements; short-circuits on the first
        violation.
        """
        elems = list(self.elements)
        for i, a in enumerate(elems):
            for b in elems[i + 1 :]:
                if self.operation(a, b) != self.operation(b, a):
                    return False
        return True

    def powers(self, a: Hashable) -> list[Hashable]:
        """Return ``[e, a, a², …]`` including the final identity.

        For an element of order *k*, returns a list of length ``k + 1``.
        """
        result: list[Hashable] = []
        current = self.identity
        for _ in range(self.order()):
            result.append(current)
            current = self.operation(a, current)
            if current == self.identity:
                result.append(current)
                break
        return result

    def order_of(self, a: Hashable) -> int:
        """Return the order of element *a* (smallest positive *k* with aᵏ = e)."""
        p = self.powers(a)
        # powers ends with identity; order is length minus 1
        # (subtract the initial identity)
        return len(p) - 1 or 1

    def subgroups(self) -> Set["Group"]:
        """Enumerate all subgroups via brute-force closure.

        For small groups this is fine; for |G| > 15 you probably want
        a smarter algorithm.
        """
        elems = list(self.elements)
        n = len(elems)
        found: set[frozenset[Hashable]] = set()
        # singleton subgroups
        found.add(frozenset(self.powers(self.identity)))
        for a in elems:
            found.add(frozenset(self.powers(a)))
        # try all subsets of size >= 2 via closure from generators
        from itertools import combinations

        for size in range(2, n + 1):
            for combo in combinations(elems, size):
                closure = self._closure(set(combo))
                if len(closure) in (1, n) or frozenset(closure) in found:
                    continue
                # verify it's actually a subgroup
                if self._is_subgroup(closure):
                    found.add(frozenset(closure))
        # always include trivial and whole group
        found.add(frozenset(elems))
        return {self._wrap(frozenset(s)) for s in found}

    # --- internal helpers --------------------------------------------------

    def _closure(self, seed: set[Hashable]) -> set[Hashable]:
        """Compute the subgroup generated by *seed*."""
        result = set(seed)
        changed = True
        while changed:
            changed = False
            new: set[Hashable] = set()
            for a in result:
                for b in result:
                    ab = self.operation(a, b)
                    if ab not in result:
                        new.add(ab)
                        changed = True
                    inv = self.inverse(a)
                    if inv not in result:
                        new.add(inv)
                        changed = True
            result |= new
            if len(result) > self.order():
                break
        return result

    def _is_subgroup(self, subset: set[Hashable]) -> bool:
        e = self.identity
        if e not in subset:
            return False
        for a in subset:
            if self.inverse(a) not in subset:
                return False
            for b in subset:
                if self.operation(a, b) not in subset:
                    return False
        return True

    def _wrap(self, elems: frozenset[Hashable]) -> "_SubgroupView":
        return _SubgroupView(self, elems)

    def __repr__(self) -> str:
        return f"{type(self).__name__}(order={self.order()})"


class _SubgroupView(Group):
    """A lightweight subgroup view backed by a parent group."""

    def __init__(self, parent: Group, elems: frozenset[Hashable]) -> None:
        self._parent = parent
        self._elems = elems

    @property
    def elements(self) -> FrozenSet[Hashable]:
        return self._elems  # type: ignore[return-value]

    def operation(self, a: Hashable, b: Hashable) -> Hashable:
        return self._parent.operation(a, b)

    @property
    def identity(self) -> Hashable:
        return self._parent.identity

    def inverse(self, a: Hashable) -> Hashable:
        return self._parent.inverse(a)

    def __eq__(self, other: object) -> bool:
        if isinstance(other, _SubgroupView):
            return self._elems == other._elems
        return NotImplemented

    def __hash__(self) -> int:
        return hash(self._elems)

    def __repr__(self) -> str:
        return f"Subgroup({set(self._elems)})"


# ---------------------------------------------------------------------------
# Concrete group families
# ---------------------------------------------------------------------------

def _perm_compose(p: tuple[int, ...], q: tuple[int, ...]) -> tuple[int, ...]:
    """Compose two permutations (right-to-left convention: (p∘q)(i) = p[q[i]])."""
    return tuple(p[q[i]] for i in range(len(p)))


def _perm_inverse(p: tuple[int, ...]) -> tuple[int, ...]:
    inv = [0] * len(p)
    for i, v in enumerate(p):
        inv[v] = i
    return tuple(inv)


class SymmetricGroup(Group):
    """The symmetric group *S_n* — all permutations of *n* objects.

    Elements are represented as tuples ``(σ(0), σ(1), …, σ(n-1))``.
    """

    def __init__(self, n: int) -> None:
        if n < 1:
            raise ValueError("n must be ≥ 1")
        self._n = n
        self._elems: frozenset[tuple[int, ...]] = frozenset(self._all_perms())

    def _all_perms(self) -> Iterator[tuple[int, ...]]:
        from itertools import permutations
        for p in permutations(range(self._n)):
            yield p

    @property
    def elements(self) -> FrozenSet[Hashable]:
        return self._elems  # type: ignore[return-value]

    def operation(self, a: Hashable, b: Hashable) -> Hashable:
        return _perm_compose(a, b)  # type: ignore[arg-type]

    @property
    def identity(self) -> Hashable:
        return tuple(range(self._n))

    def inverse(self, a: Hashable) -> Hashable:
        return _perm_inverse(a)  # type: ignore[arg-type]

    def __repr__(self) -> str:
        return f"S_{self._n}"


class CyclicGroup(Group):
    """The cyclic group *C_n* = ℤ/nℤ under addition mod *n*.

    Elements are integers ``0, 1, …, n-1``.
    """

    def __init__(self, n: int) -> None:
        if n < 1:
            raise ValueError("n must be ≥ 1")
        self._n = n
        self._elems: frozenset[int] = frozenset(range(n))

    @property
    def elements(self) -> FrozenSet[Hashable]:
        return self._elems  # type: ignore[return-value]

    def operation(self, a: Hashable, b: Hashable) -> Hashable:
        return (int(a) + int(b)) % self._n  # type: ignore[return-value]

    @property
    def identity(self) -> Hashable:
        return 0

    def inverse(self, a: Hashable) -> Hashable:
        return (-int(a)) % self._n  # type: ignore[return-value]

    def is_abelian(self) -> bool:
        return True

    def __repr__(self) -> str:
        return f"C_{self._n}"


class DihedralGroup(Group):
    """The dihedral group *D_n* — symmetries of a regular *n*-gon.

    Elements are pairs ``(k, flip)`` where ``k ∈ {0,…,n-1}`` is the
    rotation component and ``flip ∈ {0, 1}`` indicates reflection.
    """

    def __init__(self, n: int) -> None:
        if n < 3:
            raise ValueError("n must be ≥ 3 for a polygon")
        self._n = n
        self._elems: frozenset[tuple[int, int]] = frozenset(
            (k, f) for k in range(n) for f in (0, 1)
        )

    @property
    def elements(self) -> FrozenSet[Hashable]:
        return self._elems  # type: ignore[return-value]

    def operation(self, a: Hashable, b: Hashable) -> Hashable:
        k1, f1 = a  # type: ignore[misc]
        k2, f2 = b  # type: ignore[misc]
        # (k1, f1) ∘ (k2, f2) = (k1 + (-1)^f1 * k2 mod n, f1⊕f2)
        if f1 == 0:
            k = (k1 + k2) % self._n
        else:
            k = (k1 - k2) % self._n
        return (k, f1 ^ f2)

    @property
    def identity(self) -> Hashable:
        return (0, 0)

    def inverse(self, a: Hashable) -> Hashable:
        k, f = a  # type: ignore[misc]
        if f == 0:
            return ((-k) % self._n, 0)
        return (k, 1)

    def __repr__(self) -> str:
        return f"D_{self._n}"
